name: CI Workflow
on:
  push:
    branches:
        - main
jobs:
  build:  #name of the job
    runs-on: ubuntu-latest  #runner environment
    steps:
    
      - name: Checkout code #clone the code into the runner
        uses: actions/checkout@v4

      - name: Build Docker
        uses: docker/setup-buildx-actions@v4